language: ruby
rvm:
 - 1.9.3
 - 2.0.0

before_install:
  - "mysql -e 'create database tracks_test;'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"
  - "cp config/database.yml.tmpl config/database.yml"

script: "CODECLIMATE_REPO_TOKEN=5c52fdd2bbcd0734d56ddb2c3cbaac782da345273e8689d25f54a065ccc3397c bundle exec rake ci RACK_ENV=test"

bundler_args: --without development
notifications:
  email: false

